services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bluebinary-app-dev
    container_name: bluebinary-app-dev
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.env:/var/www/.env
    environment:
      - CI_ENVIRONMENT=development
      - APP_ENV=development
    depends_on:
      - redis
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: bluebinary-nginx-dev
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  
      - ./codeigniter:/var/www/html
      - ./logs-dev/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - app-network      

  redis:
    image: redis:latest
    container_name: bluebinary-redis-dev
    ports:
      - "6379:6379"
    networks:
      - app-network  
    volumes:
      - ./data-dev/redis:/data 
    command: ["redis-server"]
    restart: always


networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local